services:
  todoapi:
    image: todoapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:8000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User Id=SA;Password=NPa70W1K<#59;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "NPa70W1K<#59"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
