@TodoApi_HostAddress = http://localhost:80

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{TodoApi_HostAddress}}/api/TodoApp/all
Accept: application/json

###
GET {{TodoApi_HostAddress}}/api/TodoApp/note/7
Accept: application/json

###
### Add Note
POST {{TodoApi_HostAddress}}/api/TodoApp/AddNote
Content-Type: application/json

{
 "description": "Fazer compras no supermercado"
}

###

### Update Note
PUT {{TodoApi_HostAddress}}/api/TodoApp/10
Content-Type: application/json

{
    "description": "Revisar notas de matemática e português"
}

###

### Delete Note
DELETE {{TodoApi_HostAddress}}/api/TodoApp/9

###

### Swagger
GET {{TodoApi_HostAddress}}/swagger
